import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Convex codegen output — regenerated by `npx convex dev`, not hand-edited.
    "convex/_generated/**",
    // Independent Next.js app with its own eslint.config.mjs — see tara/README.md.
    "tara/**",
    // Design prototype runtime — not part of the Next.js app.
    "design-reference/**",
  ]),
  {
    rules: {
      // `const { userSlug: _slug, ...row } = doc` is how we drop a field on the
      // way between the demo store and a view model — the binding is deliberately unused.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
]);

export default eslintConfig;
