import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Convex codegen output — regenerated by `npx convex dev`, not hand-edited.
    "convex/_generated/**",
    // Independent Next.js app with its own eslint.config.mjs — see tara/README.md.
    "tara/**",
  ]),
]);

export default eslintConfig;
