// TARA catalogue — the authoritative dataset from the design handoff
// (handoff/design-reference/TARA Website.dc.html get PRODUCTS(), mirrored in
// handoff/BUILD-SPEC.md section 2). Prices are FINAL, VAT-inclusive EUR in cents.
// Categories follow the reference research groups; the 3 lab-supply SKUs are
// kind "supply" and render as a separate catalogue section.

export type Stock = "in" | "low" | "out";
export type ProductKind = "compound" | "supply";

export interface ProductVariant {
  label: string;
  priceCents: number;
}

export interface Product {
  /** Design-reference id (dose map, stacks, goals key off this). */
  id: string;
  slug: string;
  name: string;
  category: string;
  kind: ProductKind;
  /** e.g. "99.0%" or a dash for supplies. */
  purity: string;
  method: string;
  batch: string;
  accent: string;
  plain: string;
  stacks: string;
  format: string;
  stock: Stock;
  /** Typical research amount per draw in mcg (0 = not applicable). */
  typicalDoseMcg: number;
  variants: ProductVariant[];
}

// Research groups in catalogue render order (Supplies is a separate section).
export const CATEGORY_ORDER: string[] = ["GHRH", "Secretagogue", "Growth", "Repair", "Metabolic", "Longevity", "Antioxidant", "Nootropic", "Melanocortin", "Sexual", "Anti-inflammatory", "Blend"];
export const SUPPLIES_CATEGORY = "Supplies";

export const products: Product[] = [
  {
    id: "tesamorelin",
    slug: "tesamorelin",
    name: "Tesamorelin",
    category: "GHRH",
    kind: "compound",
    purity: "99.2%",
    method: "HPLC",
    batch: "G260701",
    accent: "linear-gradient(90deg,#1B5E20,#009B72)",
    plain: "A growth-hormone-releasing hormone (GHRH) analogue studied for reducing visceral fat and supporting body composition.",
    stacks: "Commonly researched alongside Ipamorelin for a steadier growth-hormone pulse.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 1000,
    variants: [{ label: "5 mg", priceCents: 3299 }, { label: "10 mg", priceCents: 5499 }],
  },
  {
    id: "sermorelin",
    slug: "sermorelin",
    name: "Sermorelin",
    category: "GHRH",
    kind: "compound",
    purity: "99.1%",
    method: "HPLC",
    batch: "G260741",
    accent: "linear-gradient(90deg,#009B72,#6A1B9A)",
    plain: "A shorter GHRH fragment used to study natural growth-hormone release and sleep quality.",
    stacks: "Often paired with a GHRP such as Ipamorelin to amplify the release.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 200,
    variants: [{ label: "5 mg", priceCents: 3299 }],
  },
  {
    id: "cjc1295nodac",
    slug: "cjc-1295-no-dac",
    name: "CJC-1295 (no DAC)",
    category: "GHRH",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260731",
    accent: "linear-gradient(90deg,#1B5E20,#1565C0)",
    plain: "A short-acting GHRH analogue (Mod GRF 1-29) that produces a clean, fast growth-hormone pulse.",
    stacks: "The classic partner to Ipamorelin — GHRH + GHRP is the most-studied growth combination.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 100,
    variants: [{ label: "5 mg", priceCents: 2499 }],
  },
  {
    id: "cjc1295",
    slug: "cjc-1295-dac",
    name: "CJC-1295 DAC",
    category: "GHRH",
    kind: "compound",
    purity: "98.8%",
    method: "HPLC",
    batch: "G260734",
    accent: "linear-gradient(90deg,#1B5E20,#1565C0)",
    plain: "A long-acting GHRH analogue whose DAC tail extends growth-hormone elevation for days per dose.",
    stacks: "Researched with Ipamorelin where less-frequent dosing is preferred.",
    format: "lyophilised vial",
    stock: "low",
    typicalDoseMcg: 1000,
    variants: [{ label: "2 mg", priceCents: 2699 }, { label: "5 mg", priceCents: 4199 }],
  },
  {
    id: "ipamorelin",
    slug: "ipamorelin",
    name: "Ipamorelin",
    category: "Secretagogue",
    kind: "compound",
    purity: "99.4%",
    method: "HPLC",
    batch: "G260713",
    accent: "linear-gradient(90deg,#009B72,#1565C0)",
    plain: "A selective growth-hormone secretagogue that prompts a GH pulse with minimal effect on hunger or cortisol.",
    stacks: "The go-to GHRP to stack with CJC-1295 or Tesamorelin.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 200,
    variants: [{ label: "5 mg", priceCents: 2199 }, { label: "10 mg", priceCents: 3699 }],
  },
  {
    id: "igf1lr3",
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    category: "Growth",
    kind: "compound",
    purity: "98.7%",
    method: "HPLC",
    batch: "G260748",
    accent: "linear-gradient(90deg,#1565C0,#009B72)",
    plain: "A long-acting form of insulin-like growth factor-1 studied for muscle-cell growth and repair.",
    stacks: "Sometimes researched after a GH-axis stack; advanced use only.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 40,
    variants: [{ label: "1 mg", priceCents: 6699 }],
  },
  {
    id: "pegmgf",
    slug: "peg-mgf",
    name: "PEG-MGF",
    category: "Growth",
    kind: "compound",
    purity: "98.5%",
    method: "HPLC",
    batch: "G260752",
    accent: "linear-gradient(90deg,#1565C0,#6A1B9A)",
    plain: "A pegylated mechano-growth factor studied for muscle repair after mechanical stress.",
    stacks: "Explored alongside IGF-1 LR3 in recovery research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 200,
    variants: [{ label: "2 mg", priceCents: 2799 }],
  },
  {
    id: "bpc157",
    slug: "bpc-157",
    name: "BPC-157",
    category: "Repair",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260722",
    accent: "linear-gradient(90deg,#1565C0,#6A1B9A)",
    plain: "A stable gastric peptide widely studied for tendon, gut and soft-tissue healing.",
    stacks: "Pairs with TB-500 — the two together are the most popular recovery stack (see Wolverine Blend).",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "5 mg", priceCents: 1999 }, { label: "10 mg", priceCents: 3299 }],
  },
  {
    id: "tb500",
    slug: "tb-500",
    name: "TB-500",
    category: "Repair",
    kind: "compound",
    purity: "98.6%",
    method: "HPLC",
    batch: "G260755",
    accent: "linear-gradient(90deg,#1565C0,#009B72)",
    plain: "A thymosin β4 fragment studied for cell migration, flexibility and wound repair.",
    stacks: "The classic partner to BPC-157 for injury and recovery research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 2000,
    variants: [{ label: "5 mg", priceCents: 2699 }, { label: "10 mg", priceCents: 3299 }],
  },
  {
    id: "ara290",
    slug: "ara-290",
    name: "ARA-290",
    category: "Repair",
    kind: "compound",
    purity: "98.9%",
    method: "HPLC",
    batch: "G260760",
    accent: "linear-gradient(90deg,#6A1B9A,#1565C0)",
    plain: "An EPO-derived peptide studied for nerve repair and neuropathic pain.",
    stacks: "Researched on its own; occasionally with BPC-157 for nerve-tissue work.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 2000,
    variants: [{ label: "10 mg", priceCents: 4999 }],
  },
  {
    id: "follistatin",
    slug: "follistatin-344",
    name: "Follistatin 344",
    category: "Repair",
    kind: "compound",
    purity: "98.4%",
    method: "HPLC",
    batch: "G260763",
    accent: "linear-gradient(90deg,#1B5E20,#6A1B9A)",
    plain: "A protein that binds myostatin, studied for its effect on muscle-mass regulation.",
    stacks: "A premium standalone; not typically stacked.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 100,
    variants: [{ label: "1 mg", priceCents: 9199 }],
  },
  {
    id: "retatrutide",
    slug: "retatrutide",
    name: "Retatrutide",
    category: "Metabolic",
    kind: "compound",
    purity: "99.1%",
    method: "HPLC",
    batch: "G260770",
    accent: "linear-gradient(90deg,#1B5E20,#009B72)",
    plain: "A triple GLP-1/GIP/glucagon receptor agonist studied for significant weight and metabolic outcomes.",
    stacks: "Used standalone; the most in-demand metabolic research compound.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 2000,
    variants: [{ label: "10 mg", priceCents: 9099 }, { label: "20 mg", priceCents: 14999 }, { label: "30 mg", priceCents: 19999 }, { label: "40 mg", priceCents: 25999 }, { label: "60 mg", priceCents: 34999 }],
  },
  {
    id: "tirzepatide",
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "Metabolic",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260773",
    accent: "linear-gradient(90deg,#009B72,#1565C0)",
    plain: "A dual GLP-1/GIP receptor agonist studied for blood-sugar control and weight reduction.",
    stacks: "Researched standalone; a leading metabolic compound.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 2500,
    variants: [{ label: "20 mg", priceCents: 11199 }, { label: "40 mg", priceCents: 18999 }, { label: "50 mg", priceCents: 22999 }, { label: "60 mg", priceCents: 26999 }],
  },
  {
    id: "cagrilintide",
    slug: "cagrilintide",
    name: "Cagrilintide",
    category: "Metabolic",
    kind: "compound",
    purity: "98.8%",
    method: "HPLC",
    batch: "G260776",
    accent: "linear-gradient(90deg,#1565C0,#1B5E20)",
    plain: "A long-acting amylin analogue studied for appetite regulation and satiety.",
    stacks: "Frequently researched together with a GLP-1 such as Retatrutide.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 300,
    variants: [{ label: "10 mg", priceCents: 7499 }],
  },
  {
    id: "aod9604",
    slug: "aod-9604",
    name: "AOD-9604",
    category: "Metabolic",
    kind: "compound",
    purity: "98.7%",
    method: "HPLC",
    batch: "G260781",
    accent: "linear-gradient(90deg,#009B72,#6A1B9A)",
    plain: "A modified fragment of growth hormone studied for fat metabolism without affecting blood sugar.",
    stacks: "Sometimes combined with fat-loss GHRH research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 300,
    variants: [{ label: "5 mg", priceCents: 3199 }, { label: "10 mg", priceCents: 5499 }],
  },
  {
    id: "amino1mq",
    slug: "5-amino-1mq",
    name: "5-Amino-1MQ",
    category: "Metabolic",
    kind: "compound",
    purity: "98.6%",
    method: "HPLC",
    batch: "G260786",
    accent: "linear-gradient(90deg,#B87333,#1B5E20)",
    plain: "A small molecule (NNMT inhibitor) studied for boosting cellular energy metabolism and fat cell activity.",
    stacks: "Explored alongside NAD+ in metabolic research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 50000,
    variants: [{ label: "10 mg", priceCents: 3299 }, { label: "50 mg", priceCents: 9999 }],
  },
  {
    id: "motsc",
    slug: "mots-c",
    name: "MOTS-c",
    category: "Metabolic",
    kind: "compound",
    purity: "98.9%",
    method: "HPLC",
    batch: "G260789",
    accent: "linear-gradient(90deg,#009B72,#1565C0)",
    plain: "A mitochondrial-derived peptide studied for exercise capacity and insulin sensitivity.",
    stacks: "Researched with metabolic and longevity compounds.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "10 mg", priceCents: 2999 }, { label: "40 mg", priceCents: 9999 }],
  },
  {
    id: "epithalon",
    slug: "epithalon",
    name: "Epithalon",
    category: "Longevity",
    kind: "compound",
    purity: "99.3%",
    method: "HPLC",
    batch: "G260784",
    accent: "linear-gradient(90deg,#1B5E20,#009B72)",
    plain: "A tetrapeptide studied for its effect on telomerase and cellular ageing.",
    stacks: "Often researched with NAD+ in longevity protocols.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 5000,
    variants: [{ label: "10 mg", priceCents: 2199 }, { label: "50 mg", priceCents: 6999 }],
  },
  {
    id: "nadplus",
    slug: "nad-plus",
    name: "NAD+",
    category: "Longevity",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260792",
    accent: "linear-gradient(90deg,#6A1B9A,#1565C0)",
    plain: "A coenzyme central to energy production, studied for cellular repair and ageing.",
    stacks: "Pairs with Epithalon or 5-Amino-1MQ in longevity research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 50000,
    variants: [{ label: "500 mg", priceCents: 5799 }, { label: "1000 mg", priceCents: 9999 }],
  },
  {
    id: "glutathione",
    slug: "glutathione",
    name: "Glutathione",
    category: "Antioxidant",
    kind: "compound",
    purity: "98.5%",
    method: "HPLC",
    batch: "G260795",
    accent: "linear-gradient(90deg,#009B72,#B87333)",
    plain: "The body’s master antioxidant, studied for detoxification and skin brightness.",
    stacks: "Researched alongside GHK-Cu for skin work.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 200000,
    variants: [{ label: "1500 mg", priceCents: 3299 }],
  },
  {
    id: "ss31",
    slug: "ss-31",
    name: "SS-31",
    category: "Antioxidant",
    kind: "compound",
    purity: "98.8%",
    method: "HPLC",
    batch: "G260798",
    accent: "linear-gradient(90deg,#1565C0,#6A1B9A)",
    plain: "A mitochondria-targeted peptide (Elamipretide) studied for protecting cellular energy production.",
    stacks: "Explored with MOTS-c in mitochondrial research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 5000,
    variants: [{ label: "10 mg", priceCents: 3299 }, { label: "50 mg", priceCents: 11499 }],
  },
  {
    id: "semax",
    slug: "semax",
    name: "Semax",
    category: "Nootropic",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260779",
    accent: "linear-gradient(90deg,#1565C0,#6A1B9A)",
    plain: "A peptide studied for focus, memory and neuroprotection.",
    stacks: "Frequently paired with Selank for cognition-and-calm research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 300,
    variants: [{ label: "10 mg", priceCents: 3099 }],
  },
  {
    id: "selank",
    slug: "selank",
    name: "Selank",
    category: "Nootropic",
    kind: "compound",
    purity: "98.9%",
    method: "HPLC",
    batch: "G260803",
    accent: "linear-gradient(90deg,#6A1B9A,#009B72)",
    plain: "A peptide studied for reducing anxiety while supporting clear thinking.",
    stacks: "The classic partner to Semax.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 300,
    variants: [{ label: "10 mg", priceCents: 2799 }],
  },
  {
    id: "dsip",
    slug: "dsip",
    name: "DSIP",
    category: "Nootropic",
    kind: "compound",
    purity: "98.7%",
    method: "HPLC",
    batch: "G260806",
    accent: "linear-gradient(90deg,#1B5E20,#6A1B9A)",
    plain: "Delta-sleep-inducing peptide, studied for deeper sleep and stress-hormone balance.",
    stacks: "Researched on its own for sleep quality.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 100,
    variants: [{ label: "5 mg", priceCents: 2399 }, { label: "10 mg", priceCents: 3899 }],
  },
  {
    id: "vip",
    slug: "vip",
    name: "VIP",
    category: "Nootropic",
    kind: "compound",
    purity: "98.6%",
    method: "HPLC",
    batch: "G260809",
    accent: "linear-gradient(90deg,#1565C0,#009B72)",
    plain: "Vasoactive intestinal peptide, studied for immune balance and inflammation of the airways.",
    stacks: "Advanced standalone research use.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 50,
    variants: [{ label: "5 mg", priceCents: 3599 }],
  },
  {
    id: "mt2",
    slug: "melanotan-2",
    name: "Melanotan 2",
    category: "Melanocortin",
    kind: "compound",
    purity: "98.8%",
    method: "HPLC",
    batch: "G260812",
    accent: "linear-gradient(90deg,#B87333,#6A1B9A)",
    plain: "A melanocortin agonist studied for skin pigmentation (tanning) and libido.",
    stacks: "Standalone; MT-2 is the more potent of the two Melanotans.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "10 mg", priceCents: 2399 }],
  },
  {
    id: "mt1",
    slug: "melanotan-1",
    name: "Melanotan 1",
    category: "Melanocortin",
    kind: "compound",
    purity: "98.9%",
    method: "HPLC",
    batch: "G260815",
    accent: "linear-gradient(90deg,#B87333,#1565C0)",
    plain: "A melanocortin peptide studied for tanning with a milder profile than MT-2.",
    stacks: "Researched standalone.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "10 mg", priceCents: 2699 }],
  },
  {
    id: "pt141",
    slug: "pt-141",
    name: "PT-141",
    category: "Sexual",
    kind: "compound",
    purity: "98.7%",
    method: "HPLC",
    batch: "G260818",
    accent: "linear-gradient(90deg,#6A1B9A,#B87333)",
    plain: "Bremelanotide, a melanocortin peptide studied for sexual arousal in both sexes.",
    stacks: "Standalone research compound.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 1000,
    variants: [{ label: "10 mg", priceCents: 2299 }],
  },
  {
    id: "kisspeptin",
    slug: "kisspeptin-10",
    name: "Kisspeptin-10",
    category: "Sexual",
    kind: "compound",
    purity: "98.6%",
    method: "HPLC",
    batch: "G260821",
    accent: "linear-gradient(90deg,#1B5E20,#6A1B9A)",
    plain: "A signalling peptide studied for its role in reproductive-hormone release.",
    stacks: "Researched standalone in hormone studies.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 100,
    variants: [{ label: "10 mg", priceCents: 4799 }],
  },
  {
    id: "kpv",
    slug: "kpv",
    name: "KPV",
    category: "Anti-inflammatory",
    kind: "compound",
    purity: "98.9%",
    method: "HPLC",
    batch: "G260824",
    accent: "linear-gradient(90deg,#009B72,#1B5E20)",
    plain: "A short alpha-MSH fragment studied for calming inflammation, especially in the gut.",
    stacks: "Pairs with BPC-157 for gut-health research.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "10 mg", priceCents: 3299 }],
  },
  {
    id: "ll37",
    slug: "ll-37",
    name: "LL-37",
    category: "Anti-inflammatory",
    kind: "compound",
    purity: "98.5%",
    method: "HPLC",
    batch: "G260827",
    accent: "linear-gradient(90deg,#1565C0,#B87333)",
    plain: "A natural antimicrobial peptide studied for wound defence and immune response.",
    stacks: "Advanced standalone research use.",
    format: "lyophilised vial",
    stock: "in",
    typicalDoseMcg: 100,
    variants: [{ label: "5 mg", priceCents: 3899 }],
  },
  {
    id: "wolverine",
    slug: "wolverine-blend",
    name: "Wolverine Blend",
    category: "Blend",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260830",
    accent: "linear-gradient(90deg,#1565C0,#009B72)",
    plain: "BPC-157 and TB-500 co-formulated in one vial — the most popular all-round recovery stack.",
    stacks: "Complete in itself; the two peptides work in synergy for tissue repair.",
    format: "co-lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "BPC 10 + TB 10 mg", priceCents: 3999 }],
  },
  {
    id: "glowblend",
    slug: "glow-blend",
    name: "GLOW Blend",
    category: "Blend",
    kind: "compound",
    purity: "99.1%",
    method: "HPLC",
    batch: "G260833",
    accent: "linear-gradient(90deg,#B87333,#6A1B9A)",
    plain: "GHK-Cu, BPC-157 and TB-500 together — a skin, hair and recovery research blend.",
    stacks: "Complete stack; combines repair and cosmetic peptides.",
    format: "co-lyophilised vial",
    stock: "in",
    typicalDoseMcg: 250,
    variants: [{ label: "70 mg total", priceCents: 7499 }],
  },
  {
    id: "klowblend",
    slug: "klow-blend",
    name: "KLOW Blend",
    category: "Blend",
    kind: "compound",
    purity: "99.0%",
    method: "HPLC",
    batch: "G260836",
    accent: "linear-gradient(90deg,#6A1B9A,#1565C0)",
    plain: "GHK-Cu, KPV, BPC-157 and TB-500 — a four-peptide skin and gut-recovery blend.",
    stacks: "Complete stack; the most comprehensive of the blends.",
    format: "co-lyophilised vial",
    stock: "low",
    typicalDoseMcg: 250,
    variants: [{ label: "80 mg total", priceCents: 9999 }],
  },
  {
    id: "ghrhstack",
    slug: "cjc-1295-plus-ipamorelin",
    name: "CJC-1295 + Ipamorelin",
    category: "Blend",
    kind: "compound",
    purity: "99.2%",
    method: "HPLC",
    batch: "G260839",
    accent: "linear-gradient(90deg,#1B5E20,#1565C0)",
    plain: "The definitive GHRH + GHRP growth pairing, pre-mixed in one vial.",
    stacks: "Complete stack; the most-studied growth-hormone combination.",
    format: "co-lyophilised vial",
    stock: "in",
    typicalDoseMcg: 200,
    variants: [{ label: "CJC 2 + Ipa 5 mg", priceCents: 4799 }],
  },
  {
    id: "bacwater",
    slug: "bacteriostatic-water",
    name: "Bacteriostatic Water",
    category: "Supplies",
    kind: "supply",
    purity: "—",
    method: "HPLC",
    batch: "G260842",
    accent: "linear-gradient(90deg,#55606E,#1565C0)",
    plain: "Sterile water with benzyl alcohol — the standard diluent for reconstituting any lyophilised peptide.",
    stacks: "Needed for every peptide you reconstitute.",
    format: "sterile vial",
    stock: "in",
    typicalDoseMcg: 0,
    variants: [{ label: "3 mL", priceCents: 349 }, { label: "10 mL", priceCents: 699 }],
  },
  {
    id: "aceticacid",
    slug: "acetic-acid-0-6",
    name: "Acetic Acid 0.6%",
    category: "Supplies",
    kind: "supply",
    purity: "—",
    method: "HPLC",
    batch: "G260845",
    accent: "linear-gradient(90deg,#55606E,#6A1B9A)",
    plain: "A mild acidic diluent for peptides that dissolve poorly in bacteriostatic water.",
    stacks: "Used to reconstitute stubborn peptides such as some blends.",
    format: "sterile vial",
    stock: "in",
    typicalDoseMcg: 0,
    variants: [{ label: "3 mL", priceCents: 449 }],
  },
  {
    id: "syringes",
    slug: "insulin-syringes",
    name: "Insulin Syringes",
    category: "Supplies",
    kind: "supply",
    purity: "—",
    method: "HPLC",
    batch: "G260848",
    accent: "linear-gradient(90deg,#55606E,#009B72)",
    plain: "U-100 insulin syringes for accurate measuring of reconstituted material.",
    stacks: "Pair with the reconstitution calculator to draw the right units.",
    format: "sealed pack",
    stock: "in",
    typicalDoseMcg: 0,
    variants: [{ label: "20-pack", priceCents: 899 }, { label: "40-pack", priceCents: 1599 }],
  },
];

const SUPPLY_IDS = new Set(products.filter((p) => p.kind === "supply").map((p) => p.id));

export function isSupply(p: Product): boolean {
  return SUPPLY_IDS.has(p.id);
}

/** All categories in render order, Supplies last. */
export const categories: string[] = [...CATEGORY_ORDER, SUPPLIES_CATEGORY];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function fromPriceCents(p: Product): number {
  return Math.min(...p.variants.map((v) => v.priceCents));
}

export function hasMultipleVariants(p: Product): boolean {
  return p.variants.length > 1;
}

export function searchProducts(query: string, limit = 8): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products.filter((p) => p.name.toLowerCase().includes(q)).slice(0, limit);
}
