import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Convex codegen output — regenerated by `npx convex dev`, not hand-edited.
    "convex/_generated/**",
    // Third-party design-prototype reference files from the handoff package —
    // not app code, not hand-edited. See README.md.
    "design-reference/**",
  ]),
]);

export default eslintConfig;
